import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { pathToFileURL } from 'node:url';
import { ROOT } from './openrouter.mjs';
const aliases = { agy: 'antigravity', 'agy-cli': 'antigravity-cli', openCode: 'opencode' };
export function config(agent, { root = ROOT, node = process.execPath } = {}) {
  agent = aliases[agent] ?? agent;
  const entry = path.resolve(root, 'bin/jev-ocu.mjs');
  if (agent === 'opencode') return JSON.stringify({ $schema: 'https://opencode.ai/config.json', mcp: { 'jev-ocu': { type: 'local', command: [node, entry, 'mcp'], enabled: true } } }, null, 2);
  if (['antigravity', 'antigravity-cli', 'generic', 'claude'].includes(agent)) return JSON.stringify({ mcpServers: { 'jev-ocu': { command: node, args: [entry, 'mcp'] } } }, null, 2);
  if (agent === 'codex') return `[mcp_servers.jev-ocu]\ncommand = ${JSON.stringify(node)}\nargs = [${JSON.stringify(entry)}, "mcp"]\nstartup_timeout_sec = 15\ntool_timeout_sec = 45\n`;
  if (agent === 'pi') return JSON.stringify({ extensions: [path.resolve(root, 'integrations/pi/index.ts')], skills: [path.resolve(root, 'skill/jev-ocu')] }, null, 2);
  throw new Error('Agent must be pi, agy, agy-cli, opencode, codex, claude or generic');
}
export function skillPath(agent, { home = os.homedir(), workspace } = {}) {
  agent = aliases[agent] ?? agent;
  if (workspace) return path.resolve(workspace, agent === 'pi' ? '.pi/skills/jev-ocu' : '.agents/skills/jev-ocu');
  const dirs = { pi: '.pi/agent/skills', antigravity: '.gemini/config/skills', 'antigravity-cli': '.gemini/antigravity-cli/skills', opencode: '.config/opencode/skills', codex: '.agents/skills', claude: '.claude/skills', generic: '.agents/skills' };
  if (!dirs[agent]) throw new Error('Unknown agent');
  return path.join(home, dirs[agent], 'jev-ocu');
}
/** Only writes the selected skill and Pi loader, never the user's MCP config. */
export function install(agent, { home = os.homedir(), workspace, force = false, legacy = false, root = ROOT } = {}) {
  agent = aliases[agent] ?? agent;
  const destination = skillPath(agent, { home, workspace });
  const extension = agent === 'pi' ? path.join(workspace ? path.resolve(workspace, '.pi/extensions') : path.join(home, '.pi/agent/extensions'), 'jev-ocu.ts') : null;
  for (const p of [destination, extension].filter(Boolean)) {
    if (fs.existsSync(p) && !force) throw new Error(`Already exists: ${p}; use --force to back up and replace`);
    if (fs.existsSync(p) && fs.lstatSync(p).isSymbolicLink()) throw new Error(`Refusing to replace symlink: ${p}`);
  }
  const source = path.join(root, 'skill/jev-ocu/SKILL.md');
  const skill = fs.readFileSync(source, 'utf8').replaceAll('{{REPO_DIR}}', path.resolve(root).replaceAll('\\', '/'));
  const backups = [];
  for (const p of [destination, extension].filter(Boolean)) if (fs.existsSync(p)) {
    const backup = p + '.backup-' + Date.now(); fs.renameSync(p, backup); backups.push(backup);
  }
  fs.mkdirSync(destination, { recursive: true });
  fs.writeFileSync(path.join(destination, 'SKILL.md'), skill);
  if (extension) {
    fs.mkdirSync(path.dirname(extension), { recursive: true });
    const entry = pathToFileURL(path.resolve(root, `integrations/pi/${legacy ? 'legacy' : 'index'}.ts`)).href;
    fs.writeFileSync(extension, `// Generated by Jev-ocu; keep the repository at this path.\nexport { default } from ${JSON.stringify(entry)};\n`);
  }
  return { skill: destination, extension, backups, configChanged: false };
}
